name: Consegrity
version: '1.0-SNAPSHOT'
main: goat.projectLinearity.ProjectLinearity
api-version: '1.21'
# Remain a startup plugin so the custom chunk generator loads correctly
load: STARTUP
authors: [ DiscordGoat ]
description: A Frozen Survival Minecraft Project 
depend:
  - Citizens
commands:
  regenerate:
    description: Regenerate the Consegrity world
    usage: /regenerate
    permission: consegrity.dev
  regeneratenether:
    description: Regenerate the Consegrity Nether world
    usage: /regeneratenether
    permission: consegrity.dev
  getallconsegrityadvancements:
    description: Grants advancements from specified tab(s) or all
    usage: /getallconsegrityadvancements [all|consegrity|desert|mesa|swamp|cherry|mountain|jungle ...]
    permission: consegrity.dev
  warpto:
    description: Teleport to the spawn of a world
    usage: /warpto <worldName>
    permission: consegrity.warpto
  setcustomdurability:
    description: Sets the current durability of the held item
    usage: /setcustomdurability <amount>
    permission: consegrity.durability
  setgoldendurability:
    description: Sets the golden durability of the held item
    usage: /setgoldendurability <amount>
    permission: consegrity.durability
  setmaxdurability:
    description: Sets the max durability of the held item
    usage: /setmaxdurability <amount>
    permission: consegrity.durability
  setgild:
    description: Sets the gild value on the held heirloom
    usage: /setgild <amount> [max]
    permission: consegrity.heirloom
  i:
    description: Gives yourself a custom registry item or vanilla alternative
    usage: /i <name> [vanilla]
    permission: consegrity.items
  setstat:
    description: Adjusts a player stat for testing
    usage: /setstat <oxygen|temperature> <value> [player]
    permission: consegrity.dev
  setstatrate:
    description: Sets the stat ticking multiplier
    usage: /setstatrate <multiplier>
    permission: consegrity.dev
  debugoxygen:
    description: Toggles periodic oxygen debug logging
    usage: /debugoxygen [on|off]
    permission: consegrity.dev
  setcultistpopulation:
    description: Sets the target Mountain Cultist population
    usage: /setcultistpopulation <amount>
    permission: consegrity.cultist
  spawncustommob:
    description: Spawns a registered custom mob for testing
    usage: /spawncustommob <name>
    permission: consegrity.dev
  curse:
    description: Applies a curse to a player for testing
    usage: /curse <player> <curse>
    permission: consegrity.dev
  potions:
    description: Opens the potion shears catalogue
    usage: /potions
    permission: consegrity.potions
  culinary:
    description: Opens the culinary recipe catalogue
    usage: /culinary
    permission: consegrity.culinary
  saveinventory:
    description: Saves the next chest inventory opened for a structure
    usage: /saveinventory <structure> <name>
    permission: consegrity.dev
  structuredebug:
    description: Toggles structure placement debug logging
    usage: /structuredebug <on|off|summary>
    permission: consegrity.dev
permissions:
  consegrity.dev:
    description: Allows using /regenerate
    default: op
  consegrity.warpto:
    description: Allows using /warpto
    default: op
  consegrity.durability:
    description: Allows using durability testing commands
    default: op
  consegrity.heirloom:
    description: Allows modifying heirloom gild values
    default: op
  consegrity.items:
    description: Allows using /i to spawn custom or vanilla items
    default: op
  consegrity.cultist:
    description: Allows adjusting the Mountain Cultist population
    default: op
  consegrity.potions:
    description: Allows opening the potion shears catalogue
    default: op
  consegrity.culinary:
    description: Allows opening the culinary recipe catalogue
    default: op
